version: '3'

services:
  # proxy nginx
  nginx:
    container_name: reverse_proxy
    # do not touch this
    image: nginx:alpine
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
    volumes:
        - /var/www/reverse_proxy/conf.d:/etc/nginx/conf.d
        - /var/www/reverse_proxy/certbot/conf:/etc/letsencrypt
        - /var/www/reverse_proxy/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    networks:
      - front

  certbot:
    image: certbot/certbot
    volumes:
        - /var/www/reverse_proxy/certbot/conf:/etc/letsencrypt
        - /var/www/reverse_proxy/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - front

networks:
  front:
    name: front
